/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.model.Usuario;
import javax.swing.JOptionPane;


/**
 *
 * @author aluno.saolucas
 */
public class TelaInicial extends javax.swing.JFrame {

      private Usuario usuarioLogado;
    
    
    
    public TelaInicial(Usuario u) {
        initComponents();
                this.usuarioLogado = u;

   setLocationRelativeTo(null); // Centraliza a tela
        setTitle("FitTrack - Sistema de Treinos");
    }

    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastros = new javax.swing.JMenu();
        mnTreino = new javax.swing.JMenuItem();
        mnUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnPerfil = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnSobre = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        mnCadastros.setText("Cadastros");

        mnTreino.setText("Treino");
        mnTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTreinoActionPerformed(evt);
            }
        });
        mnCadastros.add(mnTreino);

        mnUsuario.setText("Usuario");
        mnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnUsuarioActionPerformed(evt);
            }
        });
        mnCadastros.add(mnUsuario);

        jMenuBar1.add(mnCadastros);

        jMenu2.setText("Listagem");

        mnPerfil.setText("Perfil");
        mnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPerfilActionPerformed(evt);
            }
        });
        jMenu2.add(mnPerfil);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sobre");

        mnSobre.setText("Sobre");
        mnSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSobreActionPerformed(evt);
            }
        });
        jMenu3.add(mnSobre);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTreinoActionPerformed
          try {
        new telaTreino(usuarioLogado).setVisible(true); // passa o usuário
        this.dispose();
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao abrir a tela de Treinos: " + ex.getMessage());
    }
    }//GEN-LAST:event_mnTreinoActionPerformed

    private void mnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPerfilActionPerformed
 ListagemView perfil = new ListagemView(usuarioLogado);
    perfil.setVisible(true);
    }//GEN-LAST:event_mnPerfilActionPerformed

    private void mnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnUsuarioActionPerformed
         new CadastroUsu().setVisible(true);
    }//GEN-LAST:event_mnUsuarioActionPerformed

    private void mnSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSobreActionPerformed
         JOptionPane.showMessageDialog(this,
                "FitTrack - Sistema de Gerenciamento de Treinos\n"
              + "Versão 1.0\n"
              + "Desenvolvido por Pedro Flores,Gabriel Sandes,Gabriel Bandasz,Lucas Matheus,Joaquim Guedes\n"
              + "© 2025 - Todos os direitos reservados.",
                "Sobre o Sistema",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnSobreActionPerformed
 
  
    
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
        Usuario teste = new Usuario();
        teste.setNome("Teste");
        teste.setIdade(20);
        teste.setPeso(70);
        teste.setAltura(1.75);
        teste.setSenha("123");

        new TelaInicial(teste).setVisible(true);
    });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenu mnCadastros;
    private javax.swing.JMenuItem mnPerfil;
    private javax.swing.JMenuItem mnSobre;
    private javax.swing.JMenuItem mnTreino;
    private javax.swing.JMenuItem mnUsuario;
    // End of variables declaration//GEN-END:variables
}
